//Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const fs = require('fs');

describe('Calculator Tests', function () {
  this.timeout(30000);
  let driver;
  let vars;

  //Create a screenshots directory if it doesn't exist
  if (!fs.existsSync('./screenshots')) {
    fs.mkdirSync('./screenshots');
  }

  beforeEach(async function () {
    //Configure browser options (Chrome headless or Firefox)
    const browser = process.env.BROWSER || 'chrome'; // Default to firefox

    if (browser === 'chrome') {
      const chrome = require('selenium-webdriver/chrome');
      const options = new chrome.Options();
      options.addArguments('--headless', '--no-sandbox', '--disable-dev-shm-usage');
      driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build();
    } else if (browser === 'firefox') {
      driver = await new Builder().forBrowser('firefox').build();
    } else {
      throw new Error(`Unsupported browser: ${browser}`);
    }

    vars = {};
  });

  afterEach(async function () {
    if (driver) {
      //Take a screenshot
      const filename = this.currentTest.fullTitle()
        .replace(/['"]+/g, '')
        .replace(/[^a-z0-9]/gi, '_')
        .toLowerCase();
      const encodedString = await driver.takeScreenshot();
      await fs.writeFileSync(`./screenshots/${filename}.png`, encodedString, 'base64');

      //Close browser
      await driver.quit();
    }
  });

  it('Test 1: 1 + 1', async function () {
    await driver.get('http://localhost:8000/');
    await driver.manage().window().setRect({ width: 1050, height: 652 });
    await driver.findElement(By.id('num1')).click();
    await driver.findElement(By.id('num1')).sendKeys('1');
    await driver.findElement(By.id('num2')).click();
    await driver.findElement(By.id('num2')).sendKeys('1');
    await driver.findElement(By.css('button:nth-child(1)')).click();
  });

  it('Test 2: 0 + 0', async function () {
    await driver.get('http://localhost:8000/');
    await driver.manage().window().setRect({ width: 550, height: 693 });
    await driver.findElement(By.id('num1')).click();
    await driver.findElement(By.id('num1')).sendKeys('0');
    await driver.findElement(By.id('num2')).click();
    await driver.findElement(By.id('num2')).sendKeys('0');
    await driver.findElement(By.css('button:nth-child(1)')).click();
    await driver.findElement(By.css('button:nth-child(2)')).click();
  });
});
