name: Run tests

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 122
          install-dependencies: true
      - name: Install dependencies
        run: |
          cd src
          npm install
          npm install -g http-server
          
      - name: Start server and run tests
        run: |
          cd src
          # Start server in background
          http-server -p 8000 &
          SERVER_PID=$!
          
          # Wait for server to be ready
          for i in {1..30}; do
            if curl -s http://localhost:8000 > /dev/null; then
              break
            fi
            sleep 1
          done
          
          # Run tests
          npx mocha tests/*.spec.js
          
          # Cleanup
          kill $SERVER_PID
       
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/